config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :registered_applications

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :RegisteredApplications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController

  skip_before_action :verify_authenticity_token

  before_action :set_access_control_headers

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    if registered_application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = Event.new(event_params)
      @event.registered_application = registered_application
      if @event.save
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    end
  end

  def preflight
    head 200
  end

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Conotrol-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def show
    @app = RegisteredApplication.find(params[:id])
    authorize(current_user, @app)
    @events = @app.events.group_by(&:name)
  end

  def index
    authorize_user
    @apps = RegisteredApplication.where(user: current_user)
  end

  def new
    authorize_user
    @app = RegisteredApplication.new
  end

  def create
    authorize_user
    @app = RegisteredApplication.new(app_params)
    @app.user = current_user

    if @app.save
      flash[:notice] = "Application was registered"
      redirect_to @app
    else
      flash.now[:alert] = "There was an error registering your application. Please try again."
      render :new
    end
  end

  def destroy
    @app = RegisteredApplication.find(params[:id])

    authorize(current_user, @app)

    if @app.destroy
      flash[:notice] = "Registration successfully removed."
      redirect_to registered_applications_path
    else
      flash.now[:alert] = "Error removing application registration, please try again."
    end
  end

  private

    def app_params
      params.require(:registered_application).permit(:name, :url, :user)
    end

    def authorize_user
      unless current_user
        flash[:alert] = "You must be logged in to do that."
        redirect_to root_path
      end
    end

    def authorize(current_user, app)
      unless current_user.id == app.user_id
        flash[:alert] = "You are not allowed to do that."
        redirect_to root_path
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <p class="navbar-brand"><%= link_to 'Blocmetrics', root_path %></p>
        <span class="navbar-text"><%= link_to 'Registered Applications', registered_applications_path %></span>
        <span class="navbar-text navbar-right">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %></strong> |
            <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path,
            method: :delete, :class => 'navbar-link' %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
            <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
          <% end %>
      </div>
    </div>
    <div class="container">
      <% if flash[:notice] %>
        <div class="container">
          <div class="alert alert-info data-dismissible show" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= flash[:notice] %>
          </div>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger data-dismissible show" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/registered_applications/index.html.erb
<h1>
  Your Registered Applications
  <%= link_to 'Add', new_registered_application_path, type: 'button', class: 'btn btn-success' %>
</h1>
<div class="row">
  <div class="col-md-8">
    <div class="list-group justify-content-between">
      <% @apps.each do |app| %>
       <%= link_to app.name, app, class: 'list-group-item list-group-item-action' %>
      <% end %>
    </div>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class="col-md-8">
  <%= form_for(@app, url: registered_applications_path, method: :post) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "Enter registration name", class: 'form-control' %>
    </div>

    <br/>

    <%= f.label :url%>
    <%= f.text_field :url, placeholder: "Enter application URL", class: "form-control" %>

    <br/>

    <%= f.submit %>

  <% end %>
</div>  

app/views/registered_applications/show.html.erb
<h1>
  <%= @app.name %>
  <small class="text-muted">
    <%= "Created #{time_ago_in_words(@app.created_at)} ago by #{@app.user.email}" %>
  </small>
  <%= link_to 'Remove', registered_application_path(@app), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to remove this Application?'} %>
  <br/>
  <%= @app.url %>
</h1>

<div class="container">
   <%= pie_chart @app.events.group(:name).count %>
</div>

<div class="container">
  <%= line_chart @app.events.group_by_day(:created_at).count %>
</div>

app/views/welcome/index.html.erb
<h1>blocmetrics</h1>